theme: jekyll-theme-minimal
title: Christophoros Palesis
description: Christophoros Palesis (year born - year died) was a Cypriot poet. This page will tell you about his life and his contributions to Cypriot poetry. This content is maintained by his grandson John Palesis, and John's daughter Elena Palesis. A more functional page is coming soon; stay tuned!
